// src/languages.js

export const indianLanguages = [
  { code: 'en', name: 'English' },
  { code: 'as', name: 'Assamese' },
  { code: 'bn', name: 'Bengali' },
  { code: 'doi', name: 'Dogri' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'hi', name: 'Hindi' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ks', name: 'Kashmiri' },
  { code: 'kok', name: 'Konkani' },
  { code: 'mai', name: 'Maithili' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'mni', name: 'Manipuri' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ne', name: 'Nepali' },
  { code: 'or', name: 'Odia' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'sa', name: 'Sanskrit' },
  { code: 'sat', name: 'Santali' },
  { code: 'sd', name: 'Sindhi' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'ur', name: 'Urdu' },
  { code: 'bho', name: 'Bhojpuri' },
  { code: 'raj', name: 'Rajasthani' }
];

export const uiTranslations = {
  en: {
    heroText: "Pure Zari Kota Saare — The Pride of Rajasthan",
    featured: "Featured Products",
    searchResults: "Search Results for",
    loading: "Loading premium collection... ⏳",
    noSarees: "No sarees found matching your criteria.",
    previous: "← Previous",
    next: "Next →",
    page: "Page",
    // Navbar & Sidebar
    navHome: "Home",
    navProducts: "Products",
    navAbout: "About Us",
    navContact: "Contact Us",
    navSearch: "Search",
    navCart: "Cart",
    welcome: "Welcome",
    signOut: "Sign Out",
    yourAccount: "YOUR ACCOUNT",
    adminPanel: "Admin Panel",
    updateProfile: "Update Profile",
    myOrders: "My Orders",
    shopByCategory: "SHOP BY CATEGORY",
    selectCategory: "Select a Category...",
    selectSubcategory: "Select a Subcategory...",
    filterByPrice: "FILTER BY PRICE",
    minPrice: "MIN PRICE",
    maxPrice: "MAX PRICE",
    goToAdmin: "Go to Admin Panel",
    // Cart Page
    cartEmpty: "Cart is empty!",
    goBackShopping: "Go Back to Shopping",
    // Orders Page
    order: "Order",
    pending: "Pending",
    payment: "Payment",
    cancelOrder: "Cancel Order",
    trackOrder: "Track Order",
    invoice: "Invoice"
  },
  hi: {
    heroText: "प्योर ज़री कोटा साड़ी — राजस्थान का गौरव",
    featured: "प्रमुख उत्पाद",
    searchResults: "के लिए खोज परिणाम",
    loading: "प्रीमियम कलेक्शन लोड हो रहा है... ⏳",
    noSarees: "आपके सर्च से मिलती-जुलती कोई साड़ी नहीं मिली।",
    previous: "← पिछला",
    next: "अगला →",
    page: "पृष्ठ",
    navHome: "होम",
    navProducts: "उत्पाद",
    navAbout: "हमारे बारे में",
    navContact: "संपर्क करें",
    navSearch: "खोजें",
    navCart: "कार्ट",
    welcome: "स्वागत है",
    signOut: "साइन आउट",
    yourAccount: "आपका खाता",
    adminPanel: "एडमिन पैनल",
    updateProfile: "प्रोफ़ाइल अपडेट करें",
    myOrders: "मेरे ऑर्डर",
    shopByCategory: "श्रेणी के अनुसार खरीदारी",
    selectCategory: "एक श्रेणी चुनें...",
    selectSubcategory: "एक उपश्रेणी चुनें...",
    filterByPrice: "कीमत के अनुसार फ़िल्टर करें",
    minPrice: "न्यूनतम कीमत",
    maxPrice: "अधिकतम कीमत",
    goToAdmin: "एडमिन पैनल पर जाएं",
    cartEmpty: "कार्ट खाली है!",
    goBackShopping: "वापस खरीदारी पर जाएं",
    order: "ऑर्डर",
    pending: "लंबित",
    payment: "भुगतान",
    cancelOrder: "ऑर्डर रद्द करें",
    trackOrder: "ऑर्डर ट्रैक करें",
    invoice: "चालान (Invoice)"
  },
  as: {
    heroText: "বিশুদ্ধ জৰি কোটা শাৰী — ৰাজস্থানৰ গৌৰৱ",
    featured: "বিশেষ সামগ্ৰী",
    searchResults: "সন্ধানৰ ফলাফল",
    loading: "প্ৰিমিয়াম সংগ্ৰহ ল'ড হৈ আছে... ⏳",
    noSarees: "আপোনাৰ চৰ্তৰ সৈতে মিলা কোনো শাৰী পোৱা নগ'ল।",
    previous: "← পূৰ্বৱৰ্তী",
    next: "পৰৱৰ্তী →",
    page: "পৃষ্ঠা",
    navHome: "হোম",
    navProducts: "সামগ্ৰী",
    navAbout: "আমাৰ বিষয়ে",
    navContact: "যোগাযোগ কৰক",
    navSearch: "সন্ধান কৰক",
    navCart: "কাৰ্ট",
    welcome: "স্বাগতম",
    signOut: "ছাইন আউট",
    yourAccount: "আপোনাৰ একাউণ্ট",
    adminPanel: "এডমিন পেনেল",
    updateProfile: "প্ৰফাইল আপডেট কৰক",
    myOrders: "মোৰ অৰ্ডাৰ",
    shopByCategory: "শ্ৰেণী অনুসৰি বজাৰ কৰক",
    selectCategory: "এটা শ্ৰেণী বাছক...",
    selectSubcategory: "এটা উপশ্ৰেণী বাছক...",
    filterByPrice: "মূল্য অনুসৰি ফিল্টাৰ কৰক",
    minPrice: "সৰ্বনিম্ন মূল্য",
    maxPrice: "সৰ্বোচ্চ মূল্য",
    goToAdmin: "এডমিন পেনেললৈ যাওক",
    cartEmpty: "কাৰ্ট খালী!",
    goBackShopping: "বজাৰ কৰিবলৈ উভতি যাওক",
    order: "অৰ্ডাৰ",
    pending: "অমীমাংসিত",
    payment: "পৰিশোধ",
    cancelOrder: "অৰ্ডাৰ বাতিল কৰক",
    trackOrder: "অৰ্ডাৰ ট্ৰেক কৰক",
    invoice: "ইনভইচ"
  },
  bn: {
    heroText: "পিওর জরি কোটা শাড়ি — রাজস্থানের গর্ব",
    featured: "বৈশিষ্ট্যযুক্ত পণ্য",
    searchResults: "এর জন্য অনুসন্ধান ফলাফল",
    loading: "প্রিমিয়াম কালেকশন লোড হচ্ছে... ⏳",
    noSarees: "আপনার মানদণ্ডের সাথে মিলে যাওয়া কোনো শাড়ি পাওয়া যায়নি।",
    previous: "← পূর্ববর্তী",
    next: "পরবর্তী →",
    page: "পৃষ্ঠা",
    navHome: "হোম",
    navProducts: "পণ্য",
    navAbout: "আমাদের সম্পর্কে",
    navContact: "যোগাযোগ করুন",
    navSearch: "অনুসন্ধান",
    navCart: "কার্ট",
    welcome: "স্বাগতম",
    signOut: "সাইন আউট",
    yourAccount: "আপনার অ্যাকাউন্ট",
    adminPanel: "অ্যাডমিন প্যানেল",
    updateProfile: "প্রোফাইল আপডেট করুন",
    myOrders: "আমার অর্ডার",
    shopByCategory: "বিভাগ অনুযায়ী কেনাকাটা করুন",
    selectCategory: "একটি বিভাগ নির্বাচন করুন...",
    selectSubcategory: "একটি উপবিভাগ নির্বাচন করুন...",
    filterByPrice: "দাম অনুযায়ী ফিল্টার করুন",
    minPrice: "সর্বনিম্ন দাম",
    maxPrice: "সর্বোচ্চ দাম",
    goToAdmin: "অ্যাডমিন প্যানেলে যান",
    cartEmpty: "কার্ট খালি!",
    goBackShopping: "কেনাকাটায় ফিরে যান",
    order: "অর্ডার",
    pending: "অপেক্ষমান",
    payment: "পেমেন্ট",
    cancelOrder: "অর্ডার বাতিল করুন",
    trackOrder: "অর্ডার ট্র্যাক করুন",
    invoice: "চালান"
  },
  doi: {
    heroText: "प्योर ज़री कोटा साड़ी — राजस्थान दा मान",
    featured: "खास उत्पाद",
    searchResults: "दे लेई खोज नतीजे",
    loading: "प्रीमियम कलेक्शन लोड होआ करदा ऐ... ⏳",
    noSarees: "तुंदे क्राइटेरिया कन्नै मिलदी कोई साड़ी नेईं लब्भी।",
    previous: "← पिछला",
    next: "अगला →",
    page: "सफा",
    navHome: "होम",
    navProducts: "उत्पाद",
    navAbout: "साढ़े बक्खै",
    navContact: "संपर्क करो",
    navSearch: "खोज",
    navCart: "कार्ट",
    welcome: "सुआगत ऐ",
    signOut: "साइन आउट",
    yourAccount: "तुंदा खाता",
    adminPanel: "एडमिन पैनल",
    updateProfile: "प्रोफ़ाइल अपडेट करो",
    myOrders: "मेरे आर्डर",
    shopByCategory: "श्रेणी दे हिसाबै खरीददारी",
    selectCategory: "इक श्रेणी चुनो...",
    selectSubcategory: "इक उपश्रेणी चुनो...",
    filterByPrice: "मुल्ल दे हिसाबै फिल्टर",
    minPrice: "घट्टोघट्ट मुल्ल",
    maxPrice: "बद्धोबद्ध मुल्ल",
    goToAdmin: "एडमिन पैनल पर जाओ",
    cartEmpty: "कार्ट खाली ऐ!",
    goBackShopping: "वापस खरीददारी पर जाओ",
    order: "आर्डर",
    pending: "लंबित",
    payment: "भुगतान",
    cancelOrder: "आर्डर रद्द करो",
    trackOrder: "आर्डर ट्रैक करो",
    invoice: "इनवॉइस"
  },
  gu: {
    heroText: "પ્યોર ઝરી કોટા સાડી — રાજસ્થાનનું ગૌરવ",
    featured: "મુખ્ય પ્રોડક્ટ્સ",
    searchResults: "માટે શોધ પરિણામો",
    loading: "પ્રીમિયમ કલેક્શન લોડ થઈ રહ્યું છે... ⏳",
    noSarees: "તમારી પસંદગી મુજબ કોઈ સાડી મળી નથી.",
    previous: "← પાછલું",
    next: "આગળ →",
    page: "પૃષ્ઠ",
    navHome: "હોમ",
    navProducts: "પ્રોડક્ટ્સ",
    navAbout: "અમારા વિશે",
    navContact: "સંપર્ક કરો",
    navSearch: "શોધો",
    navCart: "કાર્ટ",
    welcome: "સ્વાગત છે",
    signOut: "સાઇન આઉટ",
    yourAccount: "તમારું એકાઉન્ટ",
    adminPanel: "એડમિન પેનલ",
    updateProfile: "પ્રોફાઇલ અપડેટ કરો",
    myOrders: "મારા ઓર્ડર",
    shopByCategory: "કેટેગરી મુજબ ખરીદી",
    selectCategory: "કેટેગરી પસંદ કરો...",
    selectSubcategory: "સબકેટેગરી પસંદ કરો...",
    filterByPrice: "કિંમત મુજબ ફિલ્ટર કરો",
    minPrice: "ન્યૂનતમ કિંમત",
    maxPrice: "મહત્તમ કિંમત",
    goToAdmin: "એડમિન પેનલ પર જાઓ",
    cartEmpty: "કાર્ટ ખાલી છે!",
    goBackShopping: "ખરીદી પર પાછા જાઓ",
    order: "ઓર્ડર",
    pending: "બાકી છે",
    payment: "ચુકવણી",
    cancelOrder: "ઓર્ડર રદ કરો",
    trackOrder: "ઓર્ડર ટ્રેક કરો",
    invoice: "બિલ (Invoice)"
  },
  kn: {
    heroText: "ಶುದ್ಧ ಜರಿ ಕೋಟಾ ಸೀರೆ — ರಾಜಸ್ಥಾನದ ಹೆಮ್ಮೆ",
    featured: "ವೈಶಿಷ್ಟ್ಯಪೂರ್ಣ ಉತ್ಪನ್ನಗಳು",
    searchResults: "ಇದಕ್ಕಾಗಿ ಹುಡುಕಾಟ ಫಲಿತಾಂಶಗಳು",
    loading: "ಪ್ರೀಮಿಯಂ ಸಂಗ್ರಹ ಲೋಡ್ ಆಗುತ್ತಿದೆ... ⏳",
    noSarees: "ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದುವ ಯಾವುದೇ ಸೀರೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    previous: "← ಹಿಂದಿನ",
    next: "ಮುಂದಿನ →",
    page: "ಪುಟ",
    navHome: "ಮುಖಪುಟ",
    navProducts: "ಉತ್ಪನ್ನಗಳು",
    navAbout: "ನಮ್ಮ ಬಗ್ಗೆ",
    navContact: "ಸಂಪರ್ಕಿಸಿ",
    navSearch: "ಹುಡುಕಿ",
    navCart: "ಕಾರ್ಟ್",
    welcome: "ಸ್ವಾಗತ",
    signOut: "ಸೈನ್ ಔಟ್",
    yourAccount: "ನಿಮ್ಮ ಖಾತೆ",
    adminPanel: "ಅಡ್ಮಿನ್ ಪ್ಯಾನಲ್",
    updateProfile: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ",
    myOrders: "ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    shopByCategory: "ವರ್ಗಗಳ ಮೂಲಕ ಶಾಪಿಂಗ್",
    selectCategory: "ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ...",
    selectSubcategory: "ಉಪವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ...",
    filterByPrice: "ಬೆಲೆ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    minPrice: "ಕನಿಷ್ಠ ಬೆಲೆ",
    maxPrice: "ಗರಿಷ್ಠ ಬೆಲೆ",
    goToAdmin: "ಅಡ್ಮಿನ್ ಪ್ಯಾನಲ್‌ಗೆ ಹೋಗಿ",
    cartEmpty: "ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ!",
    goBackShopping: "ಶಾಪಿಂಗ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    order: "ಆರ್ಡರ್",
    pending: "ಬಾಕಿ ಉಳಿದಿದೆ",
    payment: "ಪಾವತಿ",
    cancelOrder: "ಆರ್ಡರ್ ರದ್ದುಮಾಡಿ",
    trackOrder: "ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    invoice: "ಇನ್ವಾಯ್ಸ್"
  },
  ks: {
    heroText: "پیور زری کوٹا ساڑھی — راجستھانک فخر",
    featured: "خاص چیزیں",
    searchResults: "تلاشک نتیجہ",
    loading: "پریمیم کلیکشن لوڈ گژھان... ⏳",
    noSarees: "تہند معیار سیت رلواس کانہہ ساڑھی ملیہ نہ۔",
    previous: "← پچھلا",
    next: "اگلا →",
    page: "صفحہ",
    navHome: "ہوم",
    navProducts: "چیزیں",
    navAbout: "اسہِ متعلق",
    navContact: "رابطہ کریو",
    navSearch: "تلاش",
    navCart: "کارٹ",
    welcome: "خوش آمدید",
    signOut: "سائن آؤٹ",
    yourAccount: "تہند اکاؤنٹ",
    adminPanel: "ایڈمن پینل",
    updateProfile: "پروفائل اپڈیٹ کریو",
    myOrders: "میأن آرڈر",
    shopByCategory: "قسمس لحاظہ خریداری",
    selectCategory: "اکھ قسم وچھو...",
    selectSubcategory: "اکھ ذیلی قسم وچھو...",
    filterByPrice: "قیمتس لحاظہ فلٹر کریو",
    minPrice: "کم از کم قیمت",
    maxPrice: "زیادہ تر قیمت",
    goToAdmin: "ایڈمن پینل گژھو",
    cartEmpty: "کارٹ چھُ خالی!",
    goBackShopping: "واپس خریداری کریو",
    order: "آرڈر",
    pending: "زیر التوا",
    payment: "ادائیگی",
    cancelOrder: "آرڈر منسوخ کریو",
    trackOrder: "آرڈر ٹریک کریو",
    invoice: "رسید"
  },
  kok: {
    heroText: "प्युअर जरी कोटा साडी — राजस्थानाचो अभिमान",
    featured: "खाशेलीं उत्पादनां",
    searchResults: "हाचे खातीर सोद निकाल",
    loading: "प्रीमियम कलेक्शन लोड जाता... ⏳",
    noSarees: "तुमच्या निकशांक जुळपी खंयचीच साडी मेळ्ळी ना.",
    previous: "← फाटलें",
    next: "मुखार →",
    page: "पान",
    navHome: "होम",
    navProducts: "उत्पादनां",
    navAbout: "आमचे विशीं",
    navContact: "संपर्क करात",
    navSearch: "सोदात",
    navCart: "कार्ट",
    welcome: "येवकार",
    signOut: "साइन आउट",
    yourAccount: "तुमचें खातें",
    adminPanel: "ऍडमिन पॅनेल",
    updateProfile: "प्रोफायल अपडेट करात",
    myOrders: "म्हजे ऑर्डर",
    shopByCategory: "श्रेणी प्रमाणे खरेदी",
    selectCategory: "श्रेणी वेंचून काडात...",
    selectSubcategory: "उपश्रेणी वेंचून काडात...",
    filterByPrice: "किमती प्रमाणे फिल्टर",
    minPrice: "उण्यांत उणी किंमत",
    maxPrice: "चडांत चड किंमत",
    goToAdmin: "ऍडमिन पॅनेलाचेर वचात",
    cartEmpty: "कार्ट रिकामें आसा!",
    goBackShopping: "परत खरेदी करात",
    order: "ऑर्डर",
    pending: "प्रलंबित",
    payment: "पैसे",
    cancelOrder: "ऑर्डर रद्द करात",
    trackOrder: "ऑर्डर ट्रॅक करात",
    invoice: "इनव्हॉइस"
  },
  mai: {
    heroText: "प्योर ज़री कोटा साड़ी — राजस्थानक गौरव",
    featured: "प्रमुख उत्पाद",
    searchResults: "क लेल खोज परिणाम",
    loading: "प्रीमियम कलेक्शन लोड भ रहल अछि... ⏳",
    noSarees: "अहाँक खोज सँ मेल खाइत कोनो साड़ी नहि भेटल।",
    previous: "← पाछू",
    next: "आगू →",
    page: "पन्ना",
    navHome: "होम",
    navProducts: "उत्पाद",
    navAbout: "हमरा सभक विषय मे",
    navContact: "संपर्क करू",
    navSearch: "खोजू",
    navCart: "कार्ट",
    welcome: "स्वागत अछि",
    signOut: "साइन आउट",
    yourAccount: "अहाँक खाता",
    adminPanel: "एडमिन पैनल",
    updateProfile: "प्रोफ़ाइल अपडेट करू",
    myOrders: "हमर ऑर्डर",
    shopByCategory: "श्रेणीक अनुसार किनू",
    selectCategory: "एकटा श्रेणी चुनू...",
    selectSubcategory: "एकटा उपश्रेणी चुनू...",
    filterByPrice: "कीमतक अनुसार फ़िल्टर करू",
    minPrice: "न्यूनतम कीमत",
    maxPrice: "अधिकतम कीमत",
    goToAdmin: "एडमिन पैनल पर जाउ",
    cartEmpty: "कार्ट खाली अछि!",
    goBackShopping: "वापस किनबा लेल जाउ",
    order: "ऑर्डर",
    pending: "लंबित",
    payment: "भुगतान",
    cancelOrder: "ऑर्डर रद्द करू",
    trackOrder: "ऑर्डर ट्रैक करू",
    invoice: "चालान"
  },
  ml: {
    heroText: "ശുദ്ധമായ സരി കോട്ട സാരി — രാജസ്ഥാനെ അഭിമാനം",
    featured: "പ്രധാന ഉൽപ്പന്നങ്ങൾ",
    searchResults: "തിരയൽ ഫലങ്ങൾ",
    loading: "പ്രീമിയം ശേഖരം ലോഡുചെയ്യുന്നു... ⏳",
    noSarees: "നിങ്ങളുടെ തിരയലിന് അനുയോജ്യമായ സാരികൾ കണ്ടെത്തിയില്ല.",
    previous: "← മുമ്പത്തെ",
    next: "അടുത്തത് →",
    page: "പേജ്",
    navHome: "ഹോം",
    navProducts: "ഉൽപ്പന്നങ്ങൾ",
    navAbout: "ഞങ്ങളെക്കുറിച്ച്",
    navContact: "ബന്ധപ്പെടുക",
    navSearch: "തിരയുക",
    navCart: "കാർട്ട്",
    welcome: "സ്വാഗതം",
    signOut: "സൈൻ ഔട്ട്",
    yourAccount: "നിങ്ങളുടെ അക്കൗണ്ട്",
    adminPanel: "അഡ്മിൻ പാനൽ",
    updateProfile: "പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുക",
    myOrders: "എന്റെ ഓർഡറുകൾ",
    shopByCategory: "വിഭാഗമനുസരിച്ച് ഷോപ്പുചെയ്യുക",
    selectCategory: "ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക...",
    selectSubcategory: "ഒരു ഉപവിഭാഗം തിരഞ്ഞെടുക്കുക...",
    filterByPrice: "വിലയനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
    minPrice: "കുറഞ്ഞ വില",
    maxPrice: "കൂടിയ വില",
    goToAdmin: "അഡ്മിൻ പാനലിലേക്ക് പോകുക",
    cartEmpty: "കാർട്ട് ശൂന്യമാണ്!",
    goBackShopping: "ഷോപ്പിംഗിലേക്ക് മടങ്ങുക",
    order: "ഓർഡർ",
    pending: "തീർപ്പുകൽപ്പിച്ചിട്ടില്ല",
    payment: "പേയ്മെന്റ്",
    cancelOrder: "ഓർഡർ റദ്ദാക്കുക",
    trackOrder: "ഓർഡർ ട്രാക്ക് ചെയ്യുക",
    invoice: "ഇൻവോയ്സ്"
  },
  mni: {
    heroText: "পিওর জরী কোটা শাড়ী — রাজস্থানগী চাউথোকচবা",
    featured: "অখন্নবা পোৎলমশিং",
    searchResults: "গীদমক থিবা ফলশিং",
    loading: "প্রিমিয়ম কলেকশন লোড তৌরি... ⏳",
    noSarees: "নহাক্কী মথৌ তাবগা চান্নবা শাড়ী অমত্তা ফংদ্রে।",
    previous: "← মমাংগী",
    next: "মথংগী →",
    page: "পেজ",
    navHome: "হোম",
    navProducts: "পোৎলমশিং",
    navAbout: "ঐখোয়গী মতাংদা",
    navContact: "কন্তেক্ত তৌবীয়ু",
    navSearch: "থিবা",
    navCart: "কার্ত",
    welcome: "তরাম্না ওকচরি",
    signOut: "সাইন আউত",
    yourAccount: "নহাক্কী একাউন্ত",
    adminPanel: "এদমিন পেনেল",
    updateProfile: "প্রোফাইল অপদেত তৌবা",
    myOrders: "ঐগী ওর্দরশিং",
    shopByCategory: "কাংলুপকী মতুং ইন্না লৈবা",
    selectCategory: "কাংলুপ অমা খনবা...",
    selectSubcategory: "মখাগী কাংলুপ অমা খনবা...",
    filterByPrice: "মমলগী মতুং ইন্না ফিল্তর তৌবা",
    minPrice: "খ্বাইদগী নেম্বা মমল",
    maxPrice: "খ্বাইদগী ৱাংবা মমল",
    goToAdmin: "এদমিন পেনেলদা চৎপা",
    cartEmpty: "কার্ত হাংলি!",
    goBackShopping: "লৈবদা হঞ্জিনবা",
    order: "ওর্দর",
    pending: "পেন্দিং",
    payment: "পেমেন্ত",
    cancelOrder: "ওর্দর কেন্সেল তৌবা",
    trackOrder: "ওর্দর ত্রেক তৌবা",
    invoice: "ইনভোইস"
  },
  mr: {
    heroText: "प्युअर जरी कोटा साडी — राजस्थानचा अभिमान",
    featured: "वैशिष्ट्यपूर्ण उत्पादने",
    searchResults: "यासाठी शोध परिणाम",
    loading: "प्रीमियम कलेक्शन लोड होत आहे... ⏳",
    noSarees: "तुमच्या निकषांशी जुळणारी कोणतीही साडी आढळली नाही.",
    previous: "← मागील",
    next: "पुढील →",
    page: "पृष्ठ",
    navHome: "होम",
    navProducts: "उत्पादने",
    navAbout: "आमच्याबद्दल",
    navContact: "संपर्क साधा",
    navSearch: "शोधा",
    navCart: "कार्ट",
    welcome: "स्वागत आहे",
    signOut: "साइन आउट",
    yourAccount: "तुमचे खाते",
    adminPanel: "अॅडमिन पॅनेल",
    updateProfile: "प्रोफाइल अपडेट करा",
    myOrders: "माझ्या ऑर्डर्स",
    shopByCategory: "श्रेणीनुसार खरेदी",
    selectCategory: "श्रेणी निवडा...",
    selectSubcategory: "उपश्रेणी निवडा...",
    filterByPrice: "किमतीनुसार फिल्टर करा",
    minPrice: "किमान किंमत",
    maxPrice: "कमाल किंमत",
    goToAdmin: "अॅडमिन पॅनेलवर जा",
    cartEmpty: "कार्ट रिकामे आहे!",
    goBackShopping: "खरेदीकडे परत जा",
    order: "ऑर्डर",
    pending: "प्रलंबित",
    payment: "पेमेंट",
    cancelOrder: "ऑर्डर रद्द करा",
    trackOrder: "ऑर्डर ट्रॅक करा",
    invoice: "इनव्हॉइस"
  },
  ne: {
    heroText: "प्योर जरी कोटा साडी — राजस्थानको गौरव",
    featured: "प्रमुख उत्पादनहरू",
    searchResults: "को लागि खोज परिणामहरू",
    loading: "प्रिमियम सङ्कलन लोड हुँदैछ... ⏳",
    noSarees: "तपाईंको मापदण्डसँग मेल खाने कुनै साडी फेला परेन।",
    previous: "← अघिल्लो",
    next: "अर्को →",
    page: "पृष्ठ",
    navHome: "होम",
    navProducts: "उत्पादनहरू",
    navAbout: "हाम्रो बारेमा",
    navContact: "सम्पर्क गर्नुहोस्",
    navSearch: "खोज्नुहोस्",
    navCart: "कार्ट",
    welcome: "स्वागत छ",
    signOut: "साइन आउट",
    yourAccount: "तपाईंको खाता",
    adminPanel: "एडमिन प्यानल",
    updateProfile: "प्रोफाइल अपडेट गर्नुहोस्",
    myOrders: "मेरा अर्डरहरू",
    shopByCategory: "श्रेणी अनुसार किनमेल",
    selectCategory: "श्रेणी छान्नुहोस्...",
    selectSubcategory: "उपश्रेणी छान्नुहोस्...",
    filterByPrice: "मूल्य अनुसार फिल्टर गर्नुहोस्",
    minPrice: "न्यूनतम मूल्य",
    maxPrice: "अधिकतम मूल्य",
    goToAdmin: "एडमिन प्यानलमा जानुहोस्",
    cartEmpty: "कार्ट खाली छ!",
    goBackShopping: "किनमेलमा फर्कनुहोस्",
    order: "अर्डर",
    pending: "बाँकी छ",
    payment: "भुक्तानी",
    cancelOrder: "अर्डर रद्द गर्नुहोस्",
    trackOrder: "अर्डर ट्र्याक गर्नुहोस्",
    invoice: "बीजक (Invoice)"
  },
  or: {
    heroText: "ବିଶୁଦ୍ଧ ଜରି କୋଟା ଶାଢ଼ୀ — ରାଜସ୍ଥାନର ଗର୍ବ",
    featured: "ବିଶେଷ ଉତ୍ପାଦଗୁଡ଼ିକ",
    searchResults: "ପାଇଁ ସନ୍ଧାନ ଫଳାଫଳ",
    loading: "ପ୍ରିମିୟମ୍ ସଂଗ୍ରହ ଲୋଡ୍ ହେଉଛି... ⏳",
    noSarees: "ଆପଣଙ୍କ ସନ୍ଧାନ ସହିତ ମେଳ ଖାଉଥିବା କୌଣସି ଶାଢ଼ୀ ମିଳିଲା ନାହିଁ।",
    previous: "← ପୂର୍ବବର୍ତ୍ତୀ",
    next: "ପରବର୍ତ୍ତୀ →",
    page: "ପୃଷ୍ଠା",
    navHome: "ହୋମ୍",
    navProducts: "ଉତ୍ପାଦଗୁଡ଼ିକ",
    navAbout: "ଆମ ବିଷୟରେ",
    navContact: "ଯୋଗାଯୋଗ କରନ୍ତୁ",
    navSearch: "ସନ୍ଧାନ କରନ୍ତୁ",
    navCart: "କାର୍ଟ",
    welcome: "ସ୍ୱାଗତମ୍",
    signOut: "ସାଇନ୍ ଆଉଟ୍",
    yourAccount: "ଆପଣଙ୍କ ଖାତା",
    adminPanel: "ଆଡମିନ୍ ପ୍ୟାନେଲ୍",
    updateProfile: "ପ୍ରୋଫାଇଲ୍ ଅପଡେଟ୍ କରନ୍ତୁ",
    myOrders: "ମୋର ଅର୍ଡର",
    shopByCategory: "ଶ୍ରେଣୀ ଅନୁଯାୟୀ କିଣନ୍ତୁ",
    selectCategory: "ଏକ ଶ୍ରେଣୀ ଚୟନ କରନ୍ତୁ...",
    selectSubcategory: "ଏକ ଉପଶ୍ରେଣୀ ଚୟନ କରନ୍ତୁ...",
    filterByPrice: "ମୂଲ୍ୟ ଅନୁଯାୟୀ ଫିଲ୍ଟର୍ କରନ୍ତୁ",
    minPrice: "ସର୍ବନିମ୍ନ ମୂଲ୍ୟ",
    maxPrice: "ସର୍ବୋଚ୍ଚ ମୂଲ୍ୟ",
    goToAdmin: "ଆଡମିନ୍ ପ୍ୟାନେଲକୁ ଯାଆନ୍ତୁ",
    cartEmpty: "କାର୍ଟ ଖାଲି ଅଛି!",
    goBackShopping: "କିଣାକିଣିକୁ ଫେରିଯାଆନ୍ତୁ",
    order: "ଅର୍ଡର",
    pending: "ବିଚାରାଧୀନ",
    payment: "ପେମେଣ୍ଟ",
    cancelOrder: "ଅର୍ଡର ବାତିଲ୍ କରନ୍ତୁ",
    trackOrder: "ଅର୍ଡର ଟ୍ରାକ୍ କରନ୍ତୁ",
    invoice: "ଇନଭଏସ୍"
  },
  pa: {
    heroText: "ਪਿਓਰ ਜ਼ਰੀ ਕੋਟਾ ਸਾੜ੍ਹੀ — ਰਾਜਸਥਾਨ ਦਾ ਮਾਣ",
    featured: "ਖਾਸ ਉਤਪਾਦ",
    searchResults: "ਲਈ ਖੋਜ ਨਤੀਜੇ",
    loading: "ਪ੍ਰੀਮੀਅਮ ਕਲੈਕਸ਼ਨ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ... ⏳",
    noSarees: "ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਮੇਲ ਖਾਂਦੀ ਕੋਈ ਸਾੜ੍ਹੀ ਨਹੀਂ ਮਿਲੀ।",
    previous: "← ਪਿਛਲਾ",
    next: "ਅਗਲਾ →",
    page: "ਪੰਨਾ",
    navHome: "ਹੋਮ",
    navProducts: "ਉਤਪਾਦ",
    navAbout: "ਸਾਡੇ ਬਾਰੇ",
    navContact: "ਸੰਪਰਕ ਕਰੋ",
    navSearch: "ਖੋਜ",
    navCart: "ਕਾਰਟ",
    welcome: "ਸਵਾਗਤ ਹੈ",
    signOut: "ਸਾਈਨ ਆਊਟ",
    yourAccount: "ਤੁਹਾਡਾ ਖਾਤਾ",
    adminPanel: "ਐਡਮਿਨ ਪੈਨਲ",
    updateProfile: "ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ",
    myOrders: "ਮੇਰੇ ਆਰਡਰ",
    shopByCategory: "ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਖਰੀਦਦਾਰੀ",
    selectCategory: "ਸ਼੍ਰੇਣੀ ਚੁਣੋ...",
    selectSubcategory: "ਉਪ-ਸ਼੍ਰੇਣੀ ਚੁਣੋ...",
    filterByPrice: "ਕੀਮਤ ਅਨੁਸਾਰ ਫਿਲਟਰ",
    minPrice: "ਘੱਟੋ-ਘੱਟ ਕੀਮਤ",
    maxPrice: "ਵੱਧ ਤੋਂ ਵੱਧ ਕੀਮਤ",
    goToAdmin: "ਐਡਮਿਨ ਪੈਨਲ 'ਤੇ ਜਾਓ",
    cartEmpty: "ਕਾਰਟ ਖਾਲੀ ਹੈ!",
    goBackShopping: "ਵਾਪਸ ਖਰੀਦਦਾਰੀ 'ਤੇ ਜਾਓ",
    order: "ਆਰਡਰ",
    pending: "ਬਕਾਇਆ",
    payment: "ਭੁਗਤਾਨ",
    cancelOrder: "ਆਰਡਰ ਰੱਦ ਕਰੋ",
    trackOrder: "ਆਰਡਰ ਟ੍ਰੈਕ ਕਰੋ",
    invoice: "ਇਨਵੌਇਸ"
  },
  sa: {
    heroText: "शुद्ध जरी कोटा शाटी — राजस्थानस्य गौरवम्",
    featured: "विशिष्टानि उत्पादानि",
    searchResults: "कृते अन्वेषणपरिणामाः",
    loading: "प्रीमियम-संग्रहः लोड् भवति... ⏳",
    noSarees: "भवतः मानदण्डैः सह मेलं कुर्वन्ती कापि शाटी न प्राप्ता।",
    previous: "← पूर्वम्",
    next: "अग्रिमम् →",
    page: "पृष्ठम्",
    navHome: "गृहम्",
    navProducts: "उत्पादानि",
    navAbout: "अस्माकं विषयम्",
    navContact: "सम्पर्कं कुर्वन्तु",
    navSearch: "अन्वेषणम्",
    navCart: "कण्डोलः",
    welcome: "स्वागतम्",
    signOut: "बहिर्गच्छन्तु",
    yourAccount: "भवतः पञ्जिका",
    adminPanel: "प्रशासनपटलम्",
    updateProfile: "रूपरेखां नवीकरोतु",
    myOrders: "मम आदेशाः",
    shopByCategory: "श्रेणीक्रमेण क्रीणन्तु",
    selectCategory: "श्रेणीं चिनोतु...",
    selectSubcategory: "उपश्रेणीं चिनोतु...",
    filterByPrice: "मूल्यक्रमेण छिनोतु",
    minPrice: "न्यूनतमं मूल्यम्",
    maxPrice: "अधिकतमं मूल्यम्",
    goToAdmin: "प्रशासनपटलं गच्छन्तु",
    cartEmpty: "कण्डोलः रिक्तः अस्ति!",
    goBackShopping: "क्रयणं प्रति गच्छन्तु",
    order: "आदेशः",
    pending: "लम्बितम्",
    payment: "मूल्यदानम्",
    cancelOrder: "आदेशं खण्डयतु",
    trackOrder: "आदेशं अनुसरतु",
    invoice: "देयकम्"
  },
  sat: {
    heroText: "ᱯᱤᱭᱚᱨ ᱡᱟᱹᱨᱤ ᱠᱚᱴᱟ ᱥᱟᱹᱲᱤ — ᱨᱟᱡᱚᱥᱛᱷᱟᱱ ᱨᱮᱭᱟᱜ ᱜᱚᱨᱚᱵᱽ",
    featured: "ᱵᱟᱪᱷᱟᱣ ᱟᱠᱟᱱ ᱡᱤᱱᱤᱥᱠᱚ",
    searchResults: "ᱞᱟᱹᱜᱤᱫ ᱥᱮᱸᱫᱽᱨᱟ ᱚᱨᱡᱚ",
    loading: "ᱯᱨᱤᱢᱤᱭᱚᱢ ᱠᱚᱞᱮᱠᱥᱚᱱ ᱞᱚᱰᱚᱜ ᱠᱟᱱᱟ... ⏳",
    noSarees: "ᱟᱢᱟᱜ ᱠᱷᱚᱡᱽ ᱥᱟᱶ ᱢᱤᱞᱟᱹᱜ ᱠᱟᱱ ᱡᱟᱦᱟᱸᱱ ᱥᱟᱹᱲᱤ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ᱾",
    previous: "← ᱢᱟᱲᱟᱝ",
    next: "ᱛᱟᱭᱚᱢ →",
    page: "ᱥᱟᱦᱴᱟ",
    navHome: "ᱦᱚᱢ",
    navProducts: "ᱡᱤᱱᱤᱥᱠᱚ",
    navAbout: "ᱟᱞᱮ ᱵᱟᱵᱚᱫᱽ",
    navContact: "ᱡᱚᱜᱟᱡᱚᱜᱽ",
    navSearch: "ᱥᱮᱸᱫᱽᱨᱟ",
    navCart: "ᱠᱟᱨᱴ",
    welcome: "ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ",
    signOut: "ᱥᱟᱭᱤᱱ ᱟᱣᱩᱴ",
    yourAccount: "ᱟᱢᱟᱜ ᱟᱠᱟᱶᱴ",
    adminPanel: "ᱮᱰᱢᱤᱱ ᱯᱮᱱᱮᱞ",
    updateProfile: "ᱯᱨᱚᱯᱷᱟᱭᱤᱞ ᱟᱯᱰᱮᱴ",
    myOrders: "ᱤᱧᱟᱜ ᱚᱨᱰᱚᱨ",
    shopByCategory: "ᱠᱮᱴᱮᱜᱚᱨᱤ ᱞᱮᱠᱟᱛᱮ ᱠᱤᱨᱤᱧ",
    selectCategory: "ᱢᱤᱫ ᱠᱮᱴᱮᱜᱚᱨᱤ ᱵᱟᱪᱷᱟᱣ...",
    selectSubcategory: "ᱢᱤᱫ ᱥᱟᱵᱽ-ᱠᱮᱴᱮᱜᱚᱨᱤ ᱵᱟᱪᱷᱟᱣ...",
    filterByPrice: "ᱫᱟᱢ ᱞᱮᱠᱟᱛᱮ ᱯᱷᱤᱞᱴᱚᱨ",
    minPrice: "ᱠᱚᱢ ᱫᱟᱢ",
    maxPrice: "ᱵᱟᱹᱲᱛᱤ ᱫᱟᱢ",
    goToAdmin: "ᱮᱰᱢᱤᱱ ᱯᱮᱱᱮᱞ ᱛᱮ ᱪᱟᱞᱟᱜ",
    cartEmpty: "ᱠᱟᱨᱴ ᱠᱷᱟᱹᱞᱤ ᱜᱮᱭᱟ!",
    goBackShopping: "ᱨᱩᱣᱟᱹᱲ ᱠᱤᱨᱤᱧ",
    order: "ᱚᱨᱰᱚᱨ",
    pending: "ᱛᱟᱺᱜᱤ ᱨᱮ",
    payment: "ᱯᱮᱢᱮᱱᱴ",
    cancelOrder: "ᱚᱨᱰᱚᱨ ᱠᱮᱱᱥᱮᱞ",
    trackOrder: "ᱚᱨᱰᱚᱨ ᱴᱨᱮᱠ",
    invoice: "ᱵᱤᱞ"
  },
  sd: {
    heroText: "پيور زري ڪوٽا ساڙهي — راجسٿان جو فخر",
    featured: "خاص پراڊڪٽس",
    searchResults: "لاءِ ڳولا جا نتيجا",
    loading: "پريميم ڪليڪشن لوڊ ٿي رهيو آهي... ⏳",
    noSarees: "توهان جي معيار سان ملندڙ ڪا به ساڙهي نه ملي.",
    previous: "← پويون",
    next: "اڳيون →",
    page: "صفحو",
    navHome: "هوم",
    navProducts: "پراڊڪٽس",
    navAbout: "اسان جي باري ۾",
    navContact: "رابطو ڪريو",
    navSearch: "ڳولا",
    navCart: "ڪارٽ",
    welcome: "ڀليڪار",
    signOut: "سائن آئوٽ",
    yourAccount: "توهان جو اڪائونٽ",
    adminPanel: "ايڊمن پينل",
    updateProfile: "پروفائيل اپڊيٽ ڪريو",
    myOrders: "منهنجا آرڊر",
    shopByCategory: "ڪيٽيگري مطابق خريداري",
    selectCategory: "ڪيٽيگري چونڊيو...",
    selectSubcategory: "سب-ڪيٽيگري چونڊيو...",
    filterByPrice: "قيمت مطابق فلٽر ڪريو",
    minPrice: "گھٽ ۾ گھٽ قيمت",
    maxPrice: "وڌ ۾ وڌ قيمت",
    goToAdmin: "ايڊمن پينل تي وڃو",
    cartEmpty: "ڪارٽ خالي آهي!",
    goBackShopping: "واپس خريداري تي وڃو",
    order: "آرڊر",
    pending: "پينڊنگ",
    payment: "ادائيگي",
    cancelOrder: "آرڊر منسوخ ڪريو",
    trackOrder: "آرڊر ٽريڪ ڪريو",
    invoice: "انوائس"
  },
  ta: {
    heroText: "தூய ஜரி கோட்டா புடவை — ராஜஸ்தானின் பெருமை",
    featured: "சிறப்பு தயாரிப்புகள்",
    searchResults: "தேடல் முடிவுகள்:",
    loading: "பிரீமியம் சேகரிப்பு ஏற்றப்படுகிறது... ⏳",
    noSarees: "உங்கள் தேடலுக்கு ஏற்ற புடவைகள் எதுவும் கிடைக்கவில்லை.",
    previous: "← முந்தைய",
    next: "அடுத்தது →",
    page: "பக்கம்",
    navHome: "முகப்பு",
    navProducts: "தயாரிப்புகள்",
    navAbout: "எங்களை பற்றி",
    navContact: "தொடர்பு கொள்ள",
    navSearch: "தேடல்",
    navCart: "கார்ட்",
    welcome: "வரவேற்கிறோம்",
    signOut: "வெளியேறு",
    yourAccount: "உங்கள் கணக்கு",
    adminPanel: "நிர்வாகி குழு (Admin)",
    updateProfile: "சுயவிவரத்தை புதுப்பிக்க",
    myOrders: "என் ஆர்டர்கள்",
    shopByCategory: "வகை வாரியாக வாங்குங்கள்",
    selectCategory: "வகையைத் தேர்ந்தெடுக்கவும்...",
    selectSubcategory: "துணை வகையைத் தேர்ந்தெடுக்கவும்...",
    filterByPrice: "விலை வாரியாக வடிகட்டு",
    minPrice: "குறைந்த விலை",
    maxPrice: "அதிக விலை",
    goToAdmin: "நிர்வாகி குழுவிற்கு செல்",
    cartEmpty: "கார்ட் காலியாக உள்ளது!",
    goBackShopping: "ஷாப்பிங்கிற்கு திரும்புக",
    order: "ஆர்டர்",
    pending: "நிலுவையில் உள்ளது",
    payment: "பணம் செலுத்துதல்",
    cancelOrder: "ஆர்டரை ரத்து செய்",
    trackOrder: "ஆர்டரை ட்ராக் செய்",
    invoice: "ரசீது (Invoice)"
  },
  te: {
    heroText: "స్వచ్ఛమైన జరీ కోటా చీర — రాజస్థాన్ గర్వకారణం",
    featured: "ప్రత్యేక ఉత్పత్తులు",
    searchResults: "దీని కోసం శోధన ఫలితాలు",
    loading: "ప్రీమియం సేకరణ లోడ్ అవుతోంది... ⏳",
    noSarees: "మీ శోధనకు సరిపోయే చీరలు ఏవీ కనుగొనబడలేదు.",
    previous: "← మునుపటి",
    next: "తదుపరి →",
    page: "పేజీ",
    navHome: "హోమ్",
    navProducts: "ఉత్పత్తులు",
    navAbout: "మా గురించి",
    navContact: "సంప్రదించండి",
    navSearch: "శోధించండి",
    navCart: "కార్ట్",
    welcome: "స్వాగతం",
    signOut: "సైన్ అవుట్",
    yourAccount: "మీ ఖాతా",
    adminPanel: "అడ్మిన్ ప్యానెల్",
    updateProfile: "ప్రొఫైల్‌ను నవీకరించండి",
    myOrders: "నా ఆర్డర్‌లు",
    shopByCategory: "కేటగిరీ ద్వారా షాపింగ్",
    selectCategory: "వర్గాన్ని ఎంచుకోండి...",
    selectSubcategory: "ఉపవర్గాన్ని ఎంచుకోండి...",
    filterByPrice: "ధర ద్వారా ఫిల్టర్ చేయండి",
    minPrice: "కనీస ధర",
    maxPrice: "గరిష్ట ధర",
    goToAdmin: "అడ్మిన్ ప్యానెల్‌కు వెళ్లండి",
    cartEmpty: "కార్ట్ ఖాళీగా ఉంది!",
    goBackShopping: "షాపింగ్ కు తిరిగి వెళ్లండి",
    order: "ఆర్డర్",
    pending: "పెండింగ్‌లో ఉంది",
    payment: "చెల్లింపు",
    cancelOrder: "ఆర్డర్‌ను రద్దు చేయండి",
    trackOrder: "ఆర్డర్‌ను ట్రాక్ చేయండి",
    invoice: "ఇన్వాయిస్"
  },
  ur: {
    heroText: "پیور زری کوٹا ساڑھی — راجستھان کا فخر",
    featured: "نمایاں مصنوعات",
    searchResults: "کے لیے تلاش کے نتائج",
    loading: "پریمیم کلیکشن لوڈ ہو رہا ہے... ⏳",
    noSarees: "آپ کے معیار کے مطابق کوئی ساڑھی نہیں ملی۔",
    previous: "← پچھلا",
    next: "اگلا →",
    page: "صفحہ",
    navHome: "ہوم",
    navProducts: "مصنوعات",
    navAbout: "ہمارے بارے میں",
    navContact: "رابطہ کریں",
    navSearch: "تلاش کریں",
    navCart: "کارٹ",
    welcome: "خوش آمدید",
    signOut: "سائن آؤٹ",
    yourAccount: "آپ کا اکاؤنٹ",
    adminPanel: "ایڈمن پینل",
    updateProfile: "پروفائل اپ ڈیٹ کریں",
    myOrders: "میرے آرڈرز",
    shopByCategory: "زمرہ کے لحاظ سے خریداری",
    selectCategory: "ایک زمرہ منتخب کریں...",
    selectSubcategory: "ذیلی زمرہ منتخب کریں...",
    filterByPrice: "قیمت کے لحاظ سے فلٹر کریں",
    minPrice: "کم از کم قیمت",
    maxPrice: "زیادہ سے زیادہ قیمت",
    goToAdmin: "ایڈمن پینل پر جائیں",
    cartEmpty: "کارٹ خالی ہے!",
    goBackShopping: "خریداری پر واپس جائیں",
    order: "آرڈر",
    pending: "زیر التواء",
    payment: "ادائیگی",
    cancelOrder: "آرڈر منسوخ کریں",
    trackOrder: "آرڈر ٹریک کریں",
    invoice: "انوائس (بل)"
  },
  bho: {
    heroText: "प्योर ज़री कोटा साड़ी — राजस्थान के शान",
    featured: "प्रमुख उत्पाद",
    searchResults: "खातिर खोज परिणाम",
    loading: "प्रीमियम कलेक्शन लोड हो रहल बा... ⏳",
    noSarees: "राउर खोज से मिलत-जुलत कवनो साड़ी ना मिलल।",
    previous: "← पाछे",
    next: "आगे →",
    page: "पन्ना",
    navHome: "होम",
    navProducts: "उत्पाद",
    navAbout: "हमनी के बारे में",
    navContact: "संपर्क करीं",
    navSearch: "खोज",
    navCart: "कार्ट",
    welcome: "स्वागत बा",
    signOut: "साइन आउट",
    yourAccount: "राउर खाता",
    adminPanel: "एडमिन पैनल",
    updateProfile: "प्रोफ़ाइल अपडेट करीं",
    myOrders: "हमर ऑर्डर",
    shopByCategory: "श्रेणी के हिसाब से किनब",
    selectCategory: "श्रेणी चुनीं...",
    selectSubcategory: "उपश्रेणी चुनीं...",
    filterByPrice: "दाम के हिसाब से फिल्टर करीं",
    minPrice: "कम से कम दाम",
    maxPrice: "अधिक्तम दाम",
    goToAdmin: "एडमिन पैनल प जाईं",
    cartEmpty: "कार्ट खाली बा!",
    goBackShopping: "वापस किनबे प जाईं",
    order: "ऑर्डर",
    pending: "लंबित",
    payment: "भुगतान",
    cancelOrder: "ऑर्डर रद्द करीं",
    trackOrder: "ऑर्डर ट्रैक करीं",
    invoice: "चालान"
  },
  raj: {
    heroText: "प्योर ज़री कोटा साड़ी — राजस्थान रो गौरव",
    featured: "खास उत्पाद",
    searchResults: "रै वास्तै खोज रा नतीजा",
    loading: "प्रीमियम कलेक्शन लोड व्हे रियो है... ⏳",
    noSarees: "थांरी खोज सूँ मिळती कोई साड़ी नीं मिली।",
    previous: "← पाछै",
    next: "आगै →",
    page: "पानो",
    navHome: "होम",
    navProducts: "उत्पाद",
    navAbout: "म्हारे बारै में",
    navContact: "संपर्क करो",
    navSearch: "खोज",
    navCart: "कार्ट",
    welcome: "खम्मा घणी",
    signOut: "साइन आउट",
    yourAccount: "थांरो खातो",
    adminPanel: "एडमिन पैनल",
    updateProfile: "प्रोफ़ाइल अपडेट करो",
    myOrders: "म्हारा ऑर्डर",
    shopByCategory: "श्रेणी रै हिसाब सूं खरीददारी",
    selectCategory: "श्रेणी चुनो...",
    selectSubcategory: "उपश्रेणी चुनो...",
    filterByPrice: "कीमत रै हिसाब सूं छाणो",
    minPrice: "कम सूं कम कीमत",
    maxPrice: "बत्ती सूं बत्ती कीमत",
    goToAdmin: "एडमिन पैनल माथै जावो",
    cartEmpty: "कार्ट खाली है!",
    goBackShopping: "पाछा खरीददारी माथै जावो",
    order: "ऑर्डर",
    pending: "लंबित",
    payment: "भुगतान",
    cancelOrder: "ऑर्डर रद्द करो",
    trackOrder: "ऑर्डर ट्रैक करो",
    invoice: "रसीद (Invoice)"
  }
};